Создал каркас backend части
NorthGateVologda/NorthGateBackend pull request #4
Opened 2023-06-30 12:32 UTC by sshiae

Создал каркас backend части

2023-06-30 12:38 UTC, olgapshen commented on NorthHackathon/NorthHackathon/settings.py
> +SECRET_KEY = 'django-insecure-gi*&6cxzs_pslz&jtt$*s6kodk14abwkd5h*-z8uq&%_vgn@_f'
Это всё через секреты Docker-а.

2023-06-30 12:43 UTC, olgapshen requested changes
Явки пароли нельзя хардкодить....

2023-07-01 21:18 UTC, closed without merging

2023-07-02 10:59 UTC, olgapshen commented
А зачем закрыли то? :)

2023-07-02 19:29 UTC, sshiae commented
> А зачем закрыли то? :)

Потому что переписывал полностью Backend, Pull Request отправил уже

2023-07-02 19:52 UTC, olgapshen commented
> Потому что переписывал полностью Backend, Pull Request отправил уже

Блин... только заметила PR :)
Всё круто! Слила!